### ISSUE TITLE
Not working with vrep..

### ISSUE THREAD

**Issue by girish99** [PierreJac/Project-NAO-Control#4]
Dear Pierre, 
                     I really  liked the approach of simulating the NAO in V-REP, but i'm unable to make it, i dont know where i'm going wrong, I followed the instructions you mentioned in Read file, the error in Python is like
Posture Initialization : StandZero
Traceback (most recent call last):

  File "<ipython-input-3-2e3977e53120>", line 1, in <module>
    runfile('C:/Users/GirishkumarReddy/Downloads/Project-NAO-Control-master/Project-NAO-Control-master/Scripts/single_nao_control.py', wdir='C:/Users/GirishkumarReddy/Downloads/Project-NAO-Control-master/Project-NAO-Control-master/Scripts')

  File "C:\Python27\Lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 601, in runfile
    execfile(filename, namespace)

  File "C:\Python27\Lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 66, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/GirishkumarReddy/Downloads/Project-NAO-Control-master/Project-NAO-Control-master/Scripts/single_nao_control.py", line 38, in <module>
    postureProxy.goToPosture(posture,1.0,1.0)

  File "C:\Python27\Lib\site-packages\naoqi.py", line 301, in **call**
    return self.**wrapped**.method_missing(self.**method**, _args, *_kwargs)

  File "C:\Python27\Lib\site-packages\naoqi.py", line 371, in method_missing
    raise e

RuntimeError:   ALRobotPosture::goToPosture
    Arguments types did not match for goToPosture (resolved to '(sff)'):
  Candidate:
  goToPosture::(sf) (1)

Please help me to solve this

**Comment by hkff** [comment]
Just comment these two lines in single_nao_control.py

line 37: motionProxy.stiffnessInterpolation('Body', 1.0, 1.0)
line 38: postureProxy.goToPosture(posture,1.0,1.0)

and it works fine

**Comment by nanbaima** [comment]
Hey, Great work all.
I got the same problem, I did comment those lines, but now the NAO isn't walking, just moved the arms to the initial position.
