### ISSUE TITLE
vision_sensor.py does not work 

### ISSUE THREAD

**Issue by Ruqaiya97** [PierreJac/Project-NAO-Control#9]
Hi Sir,
While running the vision_sensor.py script, we get the following error.
Connected to remote API server
Traceback (most recent call last):
  File "vision_sensor.py", line 63, in <module>
    streamVisionSensor('NAO_vision1',clientID,0.0001)
  File "vision_sensor.py", line 23, in streamVisionSensor
    im = I.new("RGB", (resolution[0], resolution[1]), "white")
IndexError: list index out of range
Please help. Thank you in advance.

**Comment by alvimpaulo** [comment]
I fixed this error by changing the client id line to:
clientID = vrep.simxStart('127.0.0.1', 19997, True, True, 5000, 5)
